services:
  - type: web
    name: trading-bot-backend
    env: python
    buildCommand: ""
    startCommand: "python src/main.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
